### ISSUE TITLE
conda package

### ISSUE THREAD

**Issue by RoyalTS** [koaning/memo#19]
This package is really lovely! Any chance you could put it up as a conda package in addition to PyPy?

**Comment by koaning** [comment]
I might need something of a guide to help me with that, I know that somebody else made a PR for [another package that I maintain](https://scikit-lego.netlify.app/) but I wasn't directly involved. Would you be a familiar with this? 

I'm open to adding this on conda, but I prefer to automate as much as possible.

**Comment by RoyalTS** [comment]
Got no special skills in that department, unfortunately, but I understand that this makes it pretty easy to create conda packages in a semi-automatic way: https://github.com/conda-forge/conda-smithy

**Comment by xhochy** [comment]
The simplest way is to use https://github.com/conda-incubator/grayskull with `grayskull pypi memo`, adjust the generated folder slightly (e.g. add the correct usernames as a maintainer) and make a pull request to https://github.com/conda-forge/staged-recipes (move the folder generated by grayskull into `recipes/`).

@RoyalTS You can also do it yourself and don't need "burden" @koaning with the task ;) . conda-forge is a package distribution like e.g. Debian. Packagers and maintainers of the upstream source can be (and mostly are) different.

**Comment by RoyalTS** [comment]
Sometimes I feel like @xhochy is watching me... :)

If I can do this myself then let me take a crack at it whenever I find the time over the next few days!

**Comment by RoyalTS** [comment]
What's the license on this package?

**Comment by koaning** [comment]
MIT ... I realise I need to add it. Will add it tomorrow!

**Comment by RoyalTS** [comment]
Allow me :)

**Comment by RoyalTS** [comment]
Closing with reference to https://github.com/conda-forge/staged-recipes/pull/13819
